#!/bin/bash -e

# delete empty entries in the LD_LIBRARY_PATH
# i.e. change "/a/b/c:/1/2/3::/other" into "/a/b/c:/1/2/3:/other"
# if we don't do this, then ldconfig gets confused with "" as arguments of dirs
# to add to the cache
LD_LIBRARY_PATH="${LD_LIBRARY_PATH//::/:}"
# Remove leading empty element if it exists
LD_LIBRARY_PATH="${LD_LIBRARY_PATH#:}"
# Remove trailing empty element if it exists
LD_LIBRARY_PATH="${LD_LIBRARY_PATH%:}"

IFS=':' read -ra PATHS <<< "$LD_LIBRARY_PATH"
# The fake-etc directory is to allow ldconfig to unlink the
# ld.so.cache file without breaking the bind-file layout on
# the real ld.so.cache file.
mkdir -p "$SNAP_DATA/etc" "$SNAP_DATA/fake-etc"
ldconfig -v -C "$SNAP_DATA/fake-etc/ld.so.cache" "${PATHS[@]}"

# install the new ld.so.cache to the global location by
# copying it. We must not unlink the global file or the snap
# 'layout' configuration will break.
cp "$SNAP_DATA/fake-etc/ld.so.cache" "$SNAP_DATA/etc/ld.so.cache"
