name: audacity
version: 3.7.1
adopt-info: audacity
description: |
  Audacity® is a free, easy-to-use, multi-track audio editor and recorder for Windows,
  Mac OS X, GNU/Linux and other operating systems. The interface is translated into
  many languages.

  You can use Audacity to:
  * Record live audio
  * Convert tapes and records into digital recordings or CDs
  * Edit WAV, AIFF, FLAC, MP2, MP3 or Ogg Vorbis sound files
  * Cut, copy, splice or mix sounds together
  * Change the speed or pitch of a recording
  * Apply a wide range of other effects to audio recordings

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
 amd64:
 arm64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/lib/x86_64-linux-gnu/audacity:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/audacity
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/audacity:
    bind: $SNAP/usr/share/audacity
  /usr/share/locale:
    bind: $SNAP/usr/share/locale


apps:
  audacity:
    extensions: [gnome]
    command: usr/bin/audacity
    command-chain:
    - snap/command-chain/alsa-launch
    desktop: usr/share/applications/audacity.desktop
    common-id: org.audacityteam.Audacity
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - home
      - jack1
      - network
      - network-bind
      - pulseaudio
      - removable-media
      - unity7

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  audacity:
    after: [alsa-mixin]
    plugin: cmake
    source: https://github.com/audacity/audacity.git
    source-tag: Audacity-$SNAPCRAFT_PROJECT_VERSION
    parse-info: [usr/share/metainfo/audacity.appdata.xml]
    override-pull: |
      craftctl default
      sed -i -E 's|Icon=.*|Icon=/usr/share/icons/hicolor/scalable/apps/audacity.svg|' src/audacity.desktop.in
      sed -i -E 's|Exec=env UBUNTU_MENUPROXY=0 |Exec=|' src/audacity.desktop.in
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DAUDACITY_BUILD_LEVEL=2
      - -Daudacity_obey_system_dependencies=On
      - -Daudacity_conan_enabled=Off
      - -Daudacity_lib_preference=system
      - -Daudacity_has_networking=Off
      - -Daudacity_has_sentry_reporting=Off
      - -Daudacity_has_crashreports=Off
      - -Daudacity_has_updates_check=Off
      - -Daudacity_use_ffmpeg=off
      - -Daudacity_has_vst3=Off
      - -Daudacity_has_tests=Off
      - -DwxBUILD_TOOLKIT=gtk3
    build-environment:
      - PATH: /snap/bin:$PATH
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
    build-packages:
      - build-essential
      - cmake
      - curl
      - gettext
      - jq
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libflac++-dev
      - libflac-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libid3tag0-dev
      - libjack-jackd2-dev
      - libjpeg-turbo8-dev
      - liblilv-dev
      - libmad0-dev
      - libmp3lame-dev
      - libmpg123-dev
      - libogg-dev
      - libopus-dev
      - libopusfile-dev
      - libportmidi-dev
      - libportsmf-dev
      - libpulse-dev
      - libsbsms-dev
      - libserd-dev
      - libsndfile1-dev
      - libsord-dev
      - libsoundtouch-dev
      - libsoxr-dev
      - libsqlite3-dev
      - libsratom-dev
      - libsuil-dev
      - libtwolame-dev
      - libvorbis-dev
      - libwavpack-dev
      - libwxgtk3.2-dev
      - lv2-dev
      - nasm
      - portaudio19-dev
      - python3-pip
      - rapidjson-dev
      - re2c
      - uuid-dev
      - vamp-plugin-sdk
      - wget
      - zlib1g
      - zlib1g-dev
    stage-packages:
      - libavcodec60
      - libavformat60
      - libavutil58
      - libcurl4
      - libdouble-conversion3
      - libexpat1
      - libflac12t64
      - libflac++10
      - libgl1
      - libglvnd0
      - libglx0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer1.0-0
      - libid3tag0
      - libjack-jackd2-0
      - libjpeg-turbo8
      - liblilv-0-0
      - libmad0
      - libmp3lame0
      - libopus0
      - libogg0
      - libpcre2-16-0
      - libportaudio2
      - libportmidi0
      - libportsmf0t64
      - libpulse0
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libsbsms10
      - libserd-0-0
      - libsndfile1
      - libsord-0-0
      - libsoundtouch1
      - libsoxr0
      - libsqlite3-0
      - libsratom-0-0
      - libsuil-0-0
      - libtwolame0
      - libuuid1
      - libvamp-hostsdk3v5
      - libvamp-sdk2v5
      - libvorbis0a
      - libvorbisenc2
      - libwxgtk3.2-1t64
      - zlib1g
