name: Promote

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  promote:
    name: ⬆️ Promote to latest/stable
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    if: |
      ( !github.event.issue.pull_request )
      && contains(github.event.comment.body, '/promote ')
      && contains(github.event.comment.body, 'latest/stable')
      && contains(github.event.issue.body, 'latest/stable')
      && contains(github.event.*.labels.*.name, 'testing')
    steps:
      - name: ⬆️ Promote to latest/stable
        uses: snapcrafters/ci/promote-to-stable@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          store-token: ${{ secrets.SNAP_STORE_STABLE }}